### ISSUE TITLE
Depracated

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/kb-support#158]
![partial_blur (3)](https://user-images.githubusercontent.com/44024114/111146448-2062d700-8592-11eb-9902-caba9eaac85a.jpg)

**Comment by cristianraiber** [comment]
@razvanaldea89 - any progress on this?

**Comment by razvanaldea89** [comment]
@cristianraiber not yet, was concentrated on UI and functionalities. Will start on Monday

**Comment by razvanaldea89** [comment]
This might already be present in 1.5.83

**Comment by razvanaldea89** [comment]
Confirm that they are present.
