### ISSUE TITLE
Change date received / date updated

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/kb-support#163]
Into "human friendly dates"

example: https://stackoverflow.com/questions/7641791/javascript-library-for-human-friendly-relative-date-formatting

Instead of saying: Received on: 16/03/2021 at 15:16PM, we could say: **received 21 hours ago**

---

Note: on hover, we should display the exact time / date the ticket was sent in

**Comment by razvanaldea89** [comment]
Has commit https://github.com/WPChill/kb-support/commit/30cf16be010c559df62d9cec0a50323ca0c6a504

**Comment by cristianraiber** [comment]
@razvanaldea89 - 

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/7841556/113484331-6be11480-94b0-11eb-810d-78cb0b874024.png">

**Comment by cristianraiber** [comment]
This is where it would have made more sense and this is where I wanted it to be implemented. The place you've implemented it now is also OK. However, you need to change it in the place I've highlighted in the screenshot as well.

**Comment by razvanaldea89** [comment]
![image](https://user-images.githubusercontent.com/44024114/206175592-64f27531-5540-40dc-966c-fdb4b9c8e265.png)
 
New view
