### ISSUE TITLE
Email Support plugin does not work with PHP 8

### ISSUE THREAD

**Issue by scottrpaterson** [WPChill/kb-support#168]
I've been using Email Support plugin to get emails from Gmail Business for years. 

It requires passing the novalidate-cert as described here https://kb-support.com/articles/imap-options-email-support/.

PHP 7.4 and below works 100% fine. However PHP 8 seems to have broken this as emails no longer are **read** or **pulled in**.

No errors show in the log, it just does not work.

**Comment by scottrpaterson** [comment]
This definitely needs to be fixed asap. Pro customer here that's been waiting for months.

**Comment by scottrpaterson** [comment]
This needs to get fixed!

**Comment by cristianraiber** [comment]
Should be released shortly. PHP-IMAP has finally been updated to support PHP 8.1.

**Comment by scottrpaterson** [comment]
@cristianraiber Can you tell me if this plugin now supports PHP 8.1?

**Comment by cristianraiber** [comment]
@scottrpaterson - we have a beta working on php 8.1. Will be out soon.

**Comment by razvanaldea89** [comment]
Email Piping should be working with PHP 8.x now. Going to close this.
