### ISSUE TITLE
Relocate some of the reply email fields to Email Piping

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/kb-support#177]
Should relocate the following, as the response from the end-client ( if the client responds through email client the response will not get to the support agent / manager ) : 

{reply_content} - Content of the most recent reply
{reply_files} - Attach or list files attached to the ticket reply

This way, end-client will have to respond to ticket from website and the response will get to the agent.

**Comment by razvanaldea89** [comment]
In the end we should leave them right here but add a WARNING / Upsell to Email Support extension.

**Comment by cristianraiber** [comment]
Why have you changed your opinion @razvanaldea89 ?

**Comment by razvanaldea89** [comment]
@cristianraiber after a talk with @giucu91 realized that we will take away a functionality from the users. Also, it is very tricky to do backwards compatibility as the users may have used the `{reply_content}` template tag is all sorts of combinations
