### ISSUE TITLE
Predifined tags and color coded similar to github

### ISSUE THREAD

**Issue by andyluak** [WPChill/kb-support#183]
![image](https://user-images.githubusercontent.com/49715292/117102328-c821a780-ad80-11eb-9d81-e76cac3bdfac.png)

Would make it easier to see and read . Similar function on front end also when opening a ticket from there

**Comment by cristianraiber** [comment]
If we add color-coded tags similar to GitHub, then it means we're automatically positioning this as a tool for software developers. There's an entire niche of people using this that aren't software developers. I don't think it'd be wise to provide pre-defined tags or color code them.
