### ISSUE TITLE
File upload field isn't being outputted within a form

### ISSUE THREAD

**Issue by jackmcconnell** [WPChill/kb-support#189]
Using a custom submission form, I've added a file upload field but it doesn't show the `<input type="file">` when viewing the form on the front-end. 

Have tested with the default Twenty Twenty One theme and only KB Support and Easy Digital Downloads enabled and the result is the same.

Screenshot of front-end form with Inspector open: https://www.dropbox.com/s/1oqxgaa7gooey4o/Screenshot%202021-05-20%20at%2010.03.45.png?dl=0

Screenshot of form in WP Admin: https://www.dropbox.com/s/vzqcocw8mquphz7/Screenshot%202021-05-20%20at%2010.04.38.png?dl=0

**Comment by cristianraiber** [comment]
cc @razvanaldea89

**Comment by razvanaldea89** [comment]
Hey @jackmcconnell ,

Please go to Settings->Tickets->Submission Settings and enter a number bigger than 0 in the Allow File Uploads option. Will also add a notice on front so that users can see if file uploads are enabled or not.

**Comment by jackmcconnell** [comment]
@razvanaldea89 Oh wow, I wouldn't have found that. Thanks!
