### ISSUE TITLE
Tickets admin screen doesn't show any tickets

### ISSUE THREAD

**Issue by jackmcconnell** [WPChill/kb-support#190]
I have 3 tickets - two are open (authored by me and another customer) and one is closed (authored by me). 
None of them show on the Tickets screen though, and when clicking the 'New' or 'Closed' filters (see screenshot) it still shows no tickets. 

Screenshot: https://www.dropbox.com/s/8mxtlk97egnp9qo/Screenshot%202021-05-19%20at%2012.20.14.png?dl=0

**Comment by cristianraiber** [comment]
@razvanaldea89

**Comment by razvanaldea89** [comment]
Need more info about this as it should work. @jackmcconnell are you using any filters? Could you please give a list of plugins you are using?

**Comment by jackmcconnell** [comment]
@razvanaldea89 Ah, I think it has something to permissions. When I click 'Open Ticket' at the top of the All Tickets screen, it says "You do not have access to this ticket. Go Back".

**Comment by razvanaldea89** [comment]
Hey @jackmcconnell , that option is by default on, think you unchecked when you were setting up the plugin, but yes, we should add to the option description that in the case that is unchecked the admin won't be able to see the tickets. Sorry I did not respond earlier, had some electricity problems

**Comment by jackmcconnell** [comment]
@razvanaldea89 No problem. Another issue I seem to have is that I can't seem to reply to a ticket - I can now view a ticket in the WP Admin, but I can't see anywhere to leave a reply to it. Perhaps this is permissions and settings related too?

**Comment by razvanaldea89** [comment]
You need to update first. Could you please update the ticket ( click the update button ) and see if the reply field shows up? This, along with many more, will be fixed/changed soon when we will release the update with the complete new UI. You can check it here https://github.com/WPChill/kb-support/tree/1.5.5 ( warning: not complete yet, only to see how it will look )

**Comment by jackmcconnell** [comment]
@razvanaldea89 Ah, ok. Yes, I see that now. Looking forward to seeing the 1.5.5 release.
