### ISSUE TITLE
Don't collapse most recent, non-agent reply in WP Admin

### ISSUE THREAD

**Issue by jackmcconnell** [WPChill/kb-support#191]
In the WP Admin, it is not immediately clear if a customer has replied as all of the replies are collapsed. 
There is an option to change this for the front-end but doesn't appear one to be for the WP Admin. 

It would be useful if the latest reply, if not made by a support agent, is no collapse by default.

**Comment by razvanaldea89** [comment]
Each user/agent has an option to select how many replies to expand by going to WP Users->Profile. At the bottom you have the option called "Replies to expand". However, in the new UI all replies will be expanded and it will be similar to a "Chat like" display.

**Comment by jackmcconnell** [comment]
@razvanaldea89 Perfect, thanks!
