### ISSUE TITLE
email error

### ISSUE THREAD

**Issue by mplusb** [WPChill/kb-support#199]
I have a problem with plugin, when I send a ticket site informs me of an error like below, ticked is palaced but there is no any email information, server is on xampp

https://wordpress.org/support/topic/email-error-16/#post-15221426

**Comment by TeoAlex** [comment]
Issue was fixed here https://github.com/WPChill/kb-support/commit/491c6838611a524b5cbe77d452a44f3e720f84c6 in relation to this https://github.com/WPChill/kb-support/issues/213
