### ISSUE TITLE
Add a LITE vs PRO page

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/kb-support#210]
**Is your feature request related to a problem? Please describe.**
Add a LITE vs PRO page similar to the ones we have on Download Monitor/RSVP/Modula

**Comment by razvanaldea89** [comment]
@TeoAlex why this change https://github.com/WPChill/kb-support/commit/daa98175d0fafebd3e9e061ba597724a7744176c#diff-194dc9441cbeb136dab11c7bfc6bfdd0ee0189915d05926297a1383d97278534R11 ?

**Comment by TeoAlex** [comment]
![image](https://github.com/WPChill/kb-support/assets/19348508/5de3c7bd-979e-45e6-a268-0f397fcb84ce)
Without that change the color of the Lite vs PRO link won't change because we don't load the css on all admin pages.
