### ISSUE TITLE
Increase number of characters allowed for the ticket ID

### ISSUE THREAD

**Issue by mplusb** [WPChill/kb-support#219]
**Is your feature request related to a problem? Please describe.**
The current number of my tickets has reached 1000 but I don’t see the numbering correctly as I am using the prefix “DD-” (see attached screenshot), and then the current number 1000 is “DD-000” and this is the same numbering as my old first ticket “DD-000”.

**Describe the solution you'd like**
Could you please increase the number of characters allowed for the ticket ID in the next plugin update?

**Additional context**

**Comment by TeoAlex** [comment]
The issue could not be reproduced and may have been fixed in a previous update.

**Comment by razvanaldea89** [comment]
![image](https://github.com/WPChill/kb-support/assets/44024114/6e7b30b8-6ebf-4b77-bb67-78073b531534)
