### ISSUE TITLE
KB Articles lead to a 404

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/kb-support#228]
**Describe the bug**
 I have set up a page with the [kbs_articles] shortcode, and I have three articles showing on the page, however when I click on them, they lead to a 404 page. This plugin is doing everything I need besides this.

I can provide some screenshots though.

[KB Articles in WordPress Dashboard](https://drive.google.com/file/d/1-wYOXjQsJZhgIahJ79hAc0b35p8vVJNa/view?usp=sharing)

[KB Articles on KB articles page](https://drive.google.com/file/d/1a4Fpz2iVrGzup-oeOa1X_l58vgenvG81/view?usp=sharing)

[After clicking on an article](https://drive.google.com/file/d/1wOYHrNcV1januGE0Bvb5IcyzDB6LTc7S/view?usp=sharing)

As you can see, I have added three articles, and they display just fine on the page I have specified as the KB articles page, but when I click on any of the articles, it takes me to a 404 page.

https://wordpress.org/support/topic/kb-articles-lead-to-a-404/

**Comment by razvanaldea89** [comment]
@TeoAlex think this one is a "Save permalinks" situation.

**Comment by hackthedev** [comment]
Hi i have the same issue i clicked save permalinks but still ._.

**Comment by zombxx** [comment]
Was this resolved?
