### ISSUE TITLE
Improved date readability 

### ISSUE THREAD

**Issue by BrianHenryIE** [WPChill/kb-support#245]
#163 changes the date format to use "54 days ago".

The "... ago" format is fine when the date/time is recent. It's worse UX for 54 days ago.

I know the date is available in the tool-tip \[?].

Please display the full date when significant time has passed.

Also please add the day of the week. It's quicker for me to see "Saturday" than to figure out what day it was "five days ago".

**Comment by cristianraiber** [comment]
cc @razvanaldea89
