### ISSUE TITLE
Plugin menu links under single o

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/kb-support#259]
**Is your feature request related to a problem? Please describe.**
Menu links are separated by other menu links.

**Describe the solution you'd like**
Create a single menu link from where users can go to tickets or articles.

**Describe alternatives you've considered**
While this simplifies and keeps KB Support menu links together it can also have a negative effect because although they are from the same plugin they are meant for different functionalities and can be confusing to group them.

**Additional context**
https://wordpress.org/support/topic/text-overflowing/#post-16499301

CC: @cristianraiber @giucu91 @TeoAlex

**Comment by RamseyKal** [comment]
It would be great to see this, especially since it's the same plugin. Look at what Easy Digital Downloads with v3 has done. They added spaces (horizontal lines) to separate categories in one menu. Helpful!
When WooCommerce separated menus, I found that strange and I am not happy about it. It uses more space on the left now.

**Comment by giucu91** [comment]
@razvanaldea89 @cristianraiber I think KB Articles and KB Tickes should be 2 menu entries, opinions ?

**Comment by razvanaldea89** [comment]
Agree with @giucu91, there are too many submenus to show them all.

**Comment by cristianraiber** [comment]
Agreed.

**Comment by RamseyKal** [comment]
I believe it would be helpful. I would ask users and not developers about this as user feedback is more important. Developers don't always know what users want and as a manager, I have seen that time and time again in the past decade. No offense. Here is how Easy Digital Downloads (EDD) has set up their latest menu, which looks and functions great: 
![EDD WP menu](https://github.com/WPChill/kb-support/assets/48268798/234198b7-c964-4001-be3b-4327e24afe10)

We also sell our own Newsletter and Shopping Cart plugin (at Tribulant) with 16 or 17 submenu items in one parent menu. We'll be adding separators shortly like EDD did.
![Tribulant Newsletters WP Menu](https://github.com/WPChill/kb-support/assets/48268798/c39cffed-a427-4b69-9fb0-6eb16276cc5c)

I don't believe we need 2 submenus and personally, I don't want to see 2 submenus in my WP for one plugin (I really don't like how WooCommerce does it, 4 menus! But they add white space above and below, and they have them together unlike yours where they are separated, and they are an ecommerce plugin with lots of features, though it could all be in one menu (they have multiple needless menu and submenu items that could be combined on one page)).

You could rename yours to Tickets & Articles and it should fit in one row :).

Obviously, the best would be for WordPress to allow multiple submenus in one menu :).

I hope you can reconsider. If not, then thanks nonetheless for your time.
