### ISSUE TITLE
Javascript error causing post to not save correctly when using the Classic Editor

### ISSUE THREAD

**Issue by jackmcconnell** [WPChill/kb-support#268]
**Describe the bug**
When using the Classic Editor to write or edit a post, there is a javascript error that occurs when the Publish/Update button is clicked which prevents the post from saving correctly. As such, some post meta, such as the featured image, isn't set and the post never publishes. Instead, it returns you to the Add New Post screen with nothing on it, making you think you've just lost your whole post. Going back to the All Posts screen shows it in a draft state however. 
The Block Editor works fine. 

**To Reproduce**
1. Add a new post.
2. Add a title, some post content, add a featured image, then try and publish the post.

**Expected behavior**
The post should publish with all data intact. 

**Additional context**
The error that appears in the console is:
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at HTMLInputElement.<anonymous> (admin-scripts.min.js:1:4307)
    at HTMLBodyElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)

Drilling into it, it appears to be part of `save` on an ajax call which runs when the post is being published/updated. Additionally, this should not be running when it is not on the `kbs_ticket` post type. 

**Extension version used**
 - KBS Core: 1.5.88
 - KBS Zapier: 1.0.1
 - KBS EDD: 1.1.9

**Comment by razvanaldea89** [comment]
@TeoAlex did you replicate the issue? I can't replicate it.

**Comment by TeoAlex** [comment]
I could not replicate the issue as i don't have access to the exact environment the error happened. I made some changes so kbs javascript won't load on pages where it is not needed, preventing all errors of this type on any environment.

**Comment by razvanaldea89** [comment]
@TeoAlex please check the notifications, as upon this modification you won't be able to dismiss notifications if you are not in a KB admin page.
